# MoveIt uses this configuration for controller management
trajectory_execution:
  "trajectory_execution.trajectory_duration_monitoring": False
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - niryo_arm_controller
#    - niryo_hand_controller

  niryo_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
#  niryo_hand_controller:
#    type: GripperCommand
#    joints:
#      - joint_6
#    action_ns: gripper_cmd
#    default: true
