sensors:
  - niryo_depth_camera

niryo_depth_camera:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /gazebo_depth_camera/points
  max_range: 5.0
  point_subsample: 1
  padding_offset: 0.03
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: /filtered_cloud
